# Generated by Django 6.0.1 on 2026-01-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('nit', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='NIT')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Product Code')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('features', models.JSONField(default=list, verbose_name='Features')),
                ('prices', models.JSONField(default=dict, verbose_name='Prices by Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_nit', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='infrastructure.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_nit', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='infrastructure.company', verbose_name='Company')),
                ('product', models.ForeignKey(db_column='product_code', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='infrastructure.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory',
                'ordering': ['company', 'product'],
                'unique_together': {('company', 'product')},
            },
        ),
    ]
